version: "3"

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd
    networks:
      - palisade_network
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /tmp/etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd=http://etcd:2380
  config-service:
    build: config-service
    container_name: config-service
    networks:
      - palisade_network
    healthcheck:
      test: ["CMD", "curl", "-s", "http://config-service:8080/config/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - etcd

networks:
  palisade_network: